"""FastAPI application entry point.

  uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

Provides:
- /             — welcome JSON
- /health       — unauthenticated liveness check (with configured model names)
- /v1/...       — all versioned routes (mounted via app.api.v1.router)
- /ws/voice     — WebSocket bridge (stub) for Gemini Live audio
- /docs         — Swagger UI (autogenerated)
- /openapi.json — OpenAPI schema
"""

from __future__ import annotations

import time
import uuid
from contextlib import asynccontextmanager
from typing import Any, AsyncIterator

from fastapi import FastAPI, Request, status
from fastapi.exceptions import RequestValidationError
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from starlette.exceptions import HTTPException as StarletteHTTPException

from slowapi.errors import RateLimitExceeded
from slowapi.middleware import SlowAPIMiddleware

from app.api.v1.router import v1
from app.core.config import settings
from app.core.logging import configure_logging, get_logger
from app.core.rate_limit import limiter
from app.ws.voice import router as voice_router

APP_VERSION = "0.1.0"


# ─────────────────────────────────────────────────────────────────────────────
# Lifespan: configure logging + validate config on startup
# ─────────────────────────────────────────────────────────────────────────────
@asynccontextmanager
async def lifespan(_: FastAPI) -> AsyncIterator[None]:
    configure_logging()
    log = get_logger("startup")

    # HARD GUARD: production must never run with DEV_MODE shortcuts enabled.
    # `Settings.is_dev` already returns False in production, but if the env
    # was set inconsistently we still want a loud failure at boot rather
    # than a silent footgun.
    if settings.is_production and settings.dev_mode:
        raise RuntimeError(
            "Refusing to boot: ENVIRONMENT=production with DEV_MODE=true. "
            "Set DEV_MODE=false (and don't send the X-Dev-User-Id header)."
        )
    if settings.is_production and settings.cors_origins.strip() == "*":
        raise RuntimeError(
            "Refusing to boot: ENVIRONMENT=production with CORS_ORIGINS='*'. "
            "Lock CORS_ORIGINS to your web origin(s)."
        )

    # Soft-validate critical config (warn, don't crash — allows /health
    # and unit tests to work even before secrets are wired).
    missing: list[str] = []
    if not settings.gemini_api_key.get_secret_value():
        missing.append("GEMINI_API_KEY")
    if not settings.supabase_url:
        missing.append("SUPABASE_URL")

    if missing:
        log.warning(
            "config_missing",
            keys=missing,
            note="Endpoints depending on these will 5xx until configured.",
        )
    else:
        log.info("config_ok", models=settings.model_map)

    log.info(
        "api_starting",
        host=settings.api_host,
        port=settings.api_port,
        cors_origins=settings.cors_origin_list,
        env=settings.environment,
        version=APP_VERSION,
    )
    yield
    log.info("api_stopping")


# ─────────────────────────────────────────────────────────────────────────────
# App
# ─────────────────────────────────────────────────────────────────────────────
app = FastAPI(
    title="K-12 AI Tutor API",
    version=APP_VERSION,
    description=(
        "Backend for the K-12 AI Tutor classroom — REST + SSE + WebSocket "
        "(Gemini-powered)."
    ),
    lifespan=lifespan,
    openapi_tags=[
        {"name": "health", "description": "Liveness & auth probes."},
        {"name": "courses", "description": "Curriculum tree."},
        {"name": "sessions", "description": "Lesson sessions."},
        {"name": "qa", "description": "Q&A (SSE streaming)."},
        {"name": "sketch", "description": "Chalkboard sketch analysis."},
        {"name": "quiz", "description": "Quiz generation and scoring."},
        {"name": "notes", "description": "Student notes CRUD."},
        {"name": "planner", "description": "Weekly study planner."},
        {"name": "flashcards", "description": "Spaced-repetition flashcards."},
    ],
)


# ── Rate limiting (per-user) ─────────────────────────────────────────────────
app.state.limiter = limiter


@app.exception_handler(RateLimitExceeded)
async def rate_limit_handler(request: Request, exc: RateLimitExceeded) -> JSONResponse:
    return JSONResponse(
        status_code=status.HTTP_429_TOO_MANY_REQUESTS,
        content={
            "error": "rate_limited",
            "detail": f"Too many requests. Try again in a moment ({exc.detail}).",
            "request_id": request.headers.get("x-request-id"),
        },
    )


app.add_middleware(SlowAPIMiddleware)


# ── CORS ─────────────────────────────────────────────────────────────────────
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origin_list,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
    expose_headers=["X-Request-ID"],
)


# ── Request logging middleware ───────────────────────────────────────────────
@app.middleware("http")
async def log_requests(request: Request, call_next: Any) -> Any:
    """Attach a request ID, time the response, emit a structured log line."""
    request_id = request.headers.get("x-request-id") or uuid.uuid4().hex
    start = time.perf_counter()

    response = None
    try:
        response = await call_next(request)
        return response
    finally:
        duration_ms = round((time.perf_counter() - start) * 1000, 2)
        log = get_logger("http")
        log.info(
            "request",
            request_id=request_id,
            method=request.method,
            path=request.url.path,
            status=response.status_code if response else 500,
            duration_ms=duration_ms,
        )
        if response is not None:
            response.headers["X-Request-ID"] = request_id


# ── Exception handlers ───────────────────────────────────────────────────────
@app.exception_handler(StarletteHTTPException)
async def http_exc_handler(request: Request, exc: StarletteHTTPException) -> JSONResponse:
    return JSONResponse(
        status_code=exc.status_code,
        content={
            "error": "http_error",
            "detail": exc.detail,
            "request_id": request.headers.get("x-request-id"),
        },
        headers=exc.headers or {},
    )


@app.exception_handler(RequestValidationError)
async def validation_exc_handler(
    request: Request, exc: RequestValidationError
) -> JSONResponse:
    return JSONResponse(
        status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
        content={
            "error": "validation_error",
            "detail": exc.errors(),
            "request_id": request.headers.get("x-request-id"),
        },
    )


@app.exception_handler(Exception)
async def unhandled_exc_handler(request: Request, exc: Exception) -> JSONResponse:
    log = get_logger("http")
    log.exception(
        "unhandled_exception",
        request_id=request.headers.get("x-request-id"),
        path=request.url.path,
    )
    return JSONResponse(
        status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
        content={
            "error": "internal_error",
            "detail": str(exc) if settings.is_dev else "An internal error occurred.",
            "request_id": request.headers.get("x-request-id"),
        },
    )


# ── Routes ───────────────────────────────────────────────────────────────────
@app.get("/", tags=["health"])
async def welcome() -> dict[str, Any]:
    return {
        "name": "K-12 AI Tutor API",
        "version": APP_VERSION,
        "docs": "/docs",
        "health": "/health",
    }


@app.get("/health", tags=["health"])
async def health() -> dict[str, Any]:
    """Liveness probe — also publishes configured model names."""
    return {
        "ok": True,
        "models": settings.model_map,
        "version": APP_VERSION,
    }


app.include_router(v1)
app.include_router(voice_router)
