import type { Metadata } from 'next';
import Link from 'next/link';

import { LegalPage, LegalSection } from '../_components/legal-page';

export const metadata: Metadata = {
  title: 'Terms of Service — EduMind',
  description:
    'The terms that govern use of EduMind. Draft pending legal review.',
};

/**
 * Terms of Service — static marketing page (`/terms`).
 *
 * Placeholder content for a K-12 ed-tech product. Surfaced from the sign-up
 * form. NOT legal advice — see the draft notice rendered by `LegalPage`.
 */
export default function TermsOfServicePage() {
  return (
    <LegalPage title="Terms of Service" lastUpdated="15 May 2026">
      <p>
        These terms govern the use of EduMind, an AI tutoring product for K-12
        students. By creating an account or using EduMind, you agree to these
        terms. Because EduMind is used by minors, much of this is written for
        the schools and teachers who introduce the product to students.
      </p>

      <LegalSection heading="1. Who may use EduMind">
        <p>
          EduMind is intended for students using it through a school or
          teacher, and for the teachers and administrators who manage those
          classes. Students typically join EduMind because a school or teacher
          has invited them, and the school acts as the consenting party on a
          parent&apos;s behalf.
        </p>
      </LegalSection>

      <LegalSection heading="2. Accounts">
        <p>
          You are responsible for keeping your account credentials secure and
          for activity under your account. Provide accurate information when
          signing up. We collect only the minimum needed for an account — a
          name, an email, and a password.
        </p>
      </LegalSection>

      <LegalSection heading="3. Acceptable use">
        <p>
          Use EduMind for learning. Do not attempt to disrupt the service,
          access other users&apos; data, upload harmful content, or use the
          product unlawfully. We may suspend accounts that misuse the service.
        </p>
      </LegalSection>

      <LegalSection heading="4. The AI tutor">
        <p>
          Lessons and answers are generated by an AI tutor. AI output can be
          incomplete or incorrect, and EduMind is a study aid, not a
          substitute for a teacher. Students should not rely on AI answers as
          authoritative and should not type personal information into
          questions.
        </p>
      </LegalSection>

      <LegalSection heading="5. Student data & privacy">
        <p>
          How we collect and handle student data — and the COPPA / FERPA
          considerations that apply to a product for minors — are described in
          our{' '}
          <Link
            href="/privacy"
            className="font-semibold text-indigo hover:text-indigo-deep"
          >
            Privacy Policy
          </Link>
          , which forms part of these terms.
        </p>
      </LegalSection>

      <LegalSection heading="6. Deleting your account">
        <p>
          A signed-in user can delete their account at any time from the
          account menu. Deletion removes the account and the personal data
          associated with it, as described in the Privacy Policy.
        </p>
      </LegalSection>

      <LegalSection heading="7. Changes to these terms">
        <p>
          We may update these terms as EduMind evolves. Material changes will
          be communicated to schools and users. Continued use after a change
          means you accept the updated terms.
        </p>
      </LegalSection>

      <LegalSection heading="8. Disclaimer & contact">
        <p>
          EduMind is provided on an &ldquo;as is&rdquo; basis to the extent
          permitted by law. Questions about these terms can be sent to your
          school&apos;s EduMind administrator, or to the EduMind team at the
          address provided to your school.
        </p>
      </LegalSection>
    </LegalPage>
  );
}
